---
title: "EEMB 179 Final Project Code"
author: "Sadie Cwikiel"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load any necessary packages
```

# EEMB 179 Final Project

## The effect of fishing on hysteresis in Caribbean coral reefs (Blackwood et al. 2010)
###https://link.springer.com/article/10.1007/s12080-010-0102-0

## Parameters
```{r}
### Parameters from Table 1 ###

# dimensionless parameter that determins strength of the linear relationship between coral cover and carrying capacity
z <- 0.5 

# growth rate of parrotfish (per year) estimated using the population doubling time provided in FishBase, assuming fishing pressure is absent
s <- 0.49 

# rate macroalgae directly overgrow coral per year
alpha <- 0.1

# rate macroalgae spread vegetatively over algal turfs per year
lambda <- 0.8

# rate of coral recruitment to algal turfs per year; coral always overgrow algal turfs
### ASSUMPTION WE SHOULD MENTION -- that coral overgrows algal turfs
r <- 1

# coral mortality -- natural coral mortality accounts for 2-4% per year, predation for 30%, and remaining mortality from coral disease or tissue damage following bleaching
d <- 0.44

```


```{r}
###  Variables ###

#M <- 
#C <- 
#T <- 
#P <- 
```

```{r}
### Holding vectors ###

```

```{r}
### Initial Conditions ###

```


```{r}
### other things introduced that we'll need?
#g_P <- P/beta ## not sure where they explain beta??
```


## Equations if habitat is the primary limiting resource for parrotfish (food availability as primary limiting resources is the other scenario they model)
```{r}
### Macroalgae ###
dMdt <- (alpha*M*C) - ((g_P*M)/(M + T)) + (lambda*M*T)


### Coral ###
dCdt <- (r*T*C) - (d*C) - (alpha*M*C)


### Turf algae ###
dTdt <- (g_P*M)/(M + T) - (lambda*M*T) - (r*T*C) + (d*C)


### Parrotfish ### using the equation with the squiggly P
# K(C) = C in the squiggly P equation -- relationship between parrotfish carrying capacity and coral cover
#dPdt <- s*P*(1 - (P/C))


```




