---
title: "first paper equation"
author: "Maggie Doyle"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

set up equations 
$$
\begin{align}
Macroalgae: \frac{d M}{dt}  &= \alpha M C - \frac{ gM}{(M + T)} + \gamma M T\\ 
\newline
Coral: \frac{d C}{dt} &= rTC - dC - \alpha M C\\
\newline
Turf Algae:  \frac{d T}{dt} &= \frac{ gM}{(M + T)} - \gamma M T + dC\\
\newline
Parrotfish: \frac{d P}{dt} &= s P(1 - \frac{P}{\beta K(C)}) - fP\\
\newline
\frac{d \tilde{P}}{dt} &= s \tilde{P}(1 - \frac{\tilde{P}}{K(C)}) - f\tilde{P}\\
\end{align}
$$

Parameters 
```{r}
# parrotfish growth rate
s <- 0.49 # intrinsic rate of growth s of parrotfish 

# rate macro algae directly overgrow coral per year
alpha <- 0.1 # coral overgrown by macro algae at a rate a

# rate macro algae spread vegetatively over algal turfs per year
gamma <- 0.8 # at a rate γ (gamma)

# rate of coral recruitment to algal turfs per year; coral always overgrow algal turfs
r <- 1 # corals recruit to and overgrow algal turfs at a rate r

# coral mortality -- natural coral mortality accounts for 2-4% per year, predation for 30%, and remaining mortality from coral disease or tissue damage following bleaching
d <- 0.44 # natural mortality rate of d

# grazing rate g can change, right now im setting it between the critical values 0.18 and 0.39
   # set grazing rate when it is above 0.39 coral will be in high equilibrium 
    #g <- 0.4
   # grazing rate when it is below 0.18 macroalgae will be in high equilibrium 
    #g <- 0.19
   # when grazing rate is between 0.18 and 0.39 and coral starts low, then bistability will bring back to low coral state, but when coral is high initially (above 0.5%), bistability will return to coral 
    #g <- 0.25

# maximum parrotfish carrying capacity
#beta <- C

# fishing pressure 
f <- 0

```
 
Variables 
```{r}
###  Variables ###

#M <- macroalgae 
  # M <- 1 - C - T
#C <- coral 
  # C <- 1 - M - T
#T <- turf algae 
  # T <- 1 - M - C

# M + C + T = 1 particular region of the seabed is covered entirely by macroalgae (M), coral (C), and algal turfs (T) (variables)

# g # parrotfish graze macroalgae without distinction from algal turfs at a rate g


# storing colors 
Mcol <- 'limegreen' # plot color for macropalgae 
Tcol <- 'darkolivegreen4' # plot color for turf algae 
Ccol <- 'chocolate1' # plot color for coral 
Pcol <- 'darkturquoise' #plot color for parrotfish population
```

##  Simulation 1: Original Model (no parrotfish)
mid G, low coral 
```{r}
# setting time and initial values 
# time set 0 to 100
tset <- seq(from = 0, to = 100, length.out = 20000) #set time from 0 to 100 

# set initial condition for the parameters, I just set these randomly but also to be equal to 1 as the paper says 
# M + C + T = 1 particular region of the seabed is covered entirely by macroalgae (M), coral (C), and algal turfs (T) (variables)
M0 <- .4 # macro algae starts at 40% concentration
C0  <- .4 # coral starts at 40%
T0  <- 1 - M0 - C0  # turf starts at 20% 

### Simulation 1: M, C, T dynamics in the absence of parrotfish grazing ###
g <- 0.25 #setting g to between threshold 

# creating holding vectors and filling initial conditions
M.simu <- NaN*tset 
M.simu[1] <- M0
C.simu <- NaN*tset
C.simu[1] <- C0
T.simu <- NaN*tset
T.simu[1] <- T0

#for loop for M, C, T dynamics in absence of parrotfish grazing
for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simu[i-1]
	C <- C.simu[i-1]
	Tt <- T.simu[i-1]
		

	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((g*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simu[i] <- M.simu[i-1] + dM
	C.simu[i] <- C.simu[i-1] + dC
	T.simu[i] <- 1 - C.simu[i] - M.simu[i]
}

# plot for M/C/T dynamics in the absence of parrotfish grazing
    # g = 0.4, C0 = 0.3
# plot macroalgae
plot(x = tset, y = M.simu,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Proportion of Coral, Turf and Macroalgae',
     xlim = c(min(tset), max(tset)), ylim = c(0, 1))
# plot turf
lines(x = tset, y = T.simu,
      lwd = 2, col = Tcol)
# plot coral
lines(x = tset, y = C.simu,
      lwd = 2, col = Ccol)

title("M, C, and T Dynamics Without Parrotfish \n Start with LOW Coral Cover, g = 0.25")

legend(x = 1, y = .999,
       c('Macroalgae', 'Turf Algae', 'Coral'),
       lwd = 2,
       col = c(Mcol, Tcol, Ccol))
```


mid G, high coral 
```{r}
# setting time and initial values 
# time set 0 to 100
tset <- seq(from = 0, to = 100, length.out = 20000) #set time from 0 to 100 

# set initial condition for the parameters, I just set these randomly but also to be equal to 1 as the paper says 
# M + C + T = 1 particular region of the seabed is covered entirely by macroalgae (M), coral (C), and algal turfs (T) (variables)
M0 <- .2 # macro algae starts at 50% concentration
C0  <- .65 # coral starts at 30%
T0  <- 1 - M0 - C0  # turf starts at 20% 

### Simulation 1: M, C, T dynamics in the absence of parrotfish grazing ###
g <- 0.25 #setting g to between threshold  

# creating holding vectors and filling initial conditions
M.simu1 <- NaN*tset 
M.simu1[1] <- M0
C.simu1 <- NaN*tset
C.simu1[1] <- C0
T.simu1 <- NaN*tset
T.simu1[1] <- T0

#for loop for M, C, T dynamics in absence of parrotfish grazing
for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simu1[i-1]
	C <- C.simu1[i-1]
	Tt <- T.simu1[i-1]
		

	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((g*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simu1[i] <- M.simu1[i-1] + dM
	C.simu1[i] <- C.simu1[i-1] + dC
	T.simu1[i] <- 1 - C.simu1[i] - M.simu1[i]
}

# plot for M/C/T dynamics in the absence of parrotfish grazing, HIGH coral cover 
# plot macroalgae
plot(x = tset, y = M.simu1,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Proportion of Coral, Turf and Macroalgae',
     xlim = c(min(tset), max(tset)), ylim = c(0, 1))
# plot turf
lines(x = tset, y = T.simu1,
      lwd = 2, col = Tcol)
# plot coral
lines(x = tset, y = C.simu1,
      lwd = 2, col = Ccol)

title("M, C, and T Dynamics Without Parrotfish \n Start with HIGH Coral Cover, g = 0.25")

legend(x = 60, y = 1,
       c('Macroalgae', 'Turf Algae', 'Coral'),
       lwd = 2,
       col = c(Mcol, Tcol, Ccol))
```


low coral, G above threshold 
```{r}
# setting time and initial values 
# time set 0 to 100
tset <- seq(from = 0, to = 100, length.out = 20000) #set time from 0 to 100 

# set initial condition for the parameters, I just set these randomly but also to be equal to 1 as the paper says 
# M + C + T = 1 particular region of the seabed is covered entirely by macroalgae (M), coral (C), and algal turfs (T) (variables)
M0 <- .8 # macro algae starts at 50% concentration
C0  <- .1 # coral starts at 30%
T0  <- 1 - M0 - C0  # turf starts at 20% 

### Simulation 1: M, C, T dynamics in the absence of parrotfish grazing ###
g <- 0.4 #setting g to above threshold 

# creating holding vectors and filling initial conditions
M.simuG <- NaN*tset 
M.simuG[1] <- M0
C.simuG <- NaN*tset
C.simuG[1] <- C0
T.simuG <- NaN*tset
T.simuG[1] <- T0

#for loop for M, C, T dynamics in absence of parrotfish grazing
for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simuG[i-1]
	C <- C.simuG[i-1]
	Tt <- T.simuG[i-1]
		

	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((g*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simuG[i] <- M.simuG[i-1] + dM
	C.simuG[i] <- C.simuG[i-1] + dC
	T.simuG[i] <- 1 - C.simuG[i] - M.simuG[i]
}

# plot for M/C/T dynamics in the absence of parrotfish grazing, low coral cover, high G 
# plot macroalgae
plot(x = tset, y = M.simuG,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Proportion of Coral, Turf and Macroalgae',
     xlim = c(min(tset), max(tset)), ylim = c(0, 1))
# plot turf
lines(x = tset, y = T.simuG,
      lwd = 2, col = Tcol)
# plot coral
lines(x = tset, y = C.simuG,
      lwd = 2, col = Ccol)

title("M, C, and T Dynamics Without Parrotfish \n Start with LOW Coral Cover, g = 0.4")

legend(x = 60, y = 1,
       c('Macroalgae', 'Turf Algae', 'Coral'),
       lwd = 2,
       col = c(Mcol, Tcol, Ccol))
```


high coral, G below threshold 
```{r}
# setting time and initial values 
# time set 0 to 100
tset <- seq(from = 0, to = 100, length.out = 20000) #set time from 0 to 100 

# set initial condition for the parameters, I just set these randomly but also to be equal to 1 as the paper says 
# M + C + T = 1 particular region of the seabed is covered entirely by macroalgae (M), coral (C), and algal turfs (T) (variables)
M0 <- .1 # macro algae starts at 50% concentration
C0  <- .8 # coral starts at 30%
T0  <- 1 - M0 - C0  # turf starts at 20% 

### Simulation 1: M, C, T dynamics in the absence of parrotfish grazing ###
g <- 0.17 #setting g to above threshold 

# creating holding vectors and filling initial conditions
M.simuG <- NaN*tset 
M.simuG[1] <- M0
C.simuG <- NaN*tset
C.simuG[1] <- C0
T.simuG <- NaN*tset
T.simuG[1] <- T0

#for loop for M, C, T dynamics in absence of parrotfish grazing
for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simuG[i-1]
	C <- C.simuG[i-1]
	Tt <- T.simuG[i-1]
		

	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((g*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simuG[i] <- M.simuG[i-1] + dM
	C.simuG[i] <- C.simuG[i-1] + dC
	T.simuG[i] <- 1 - C.simuG[i] - M.simuG[i]
}

# plot for M/C/T dynamics in the absence of parrotfish grazing, low coral cover, high G 
# plot macroalgae
plot(x = tset, y = M.simuG,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Proportion of Coral, Turf and Macroalgae',
     xlim = c(min(tset), max(tset)), ylim = c(0, 1))
# plot turf
lines(x = tset, y = T.simuG,
      lwd = 2, col = Tcol)
# plot coral
lines(x = tset, y = C.simuG,
      lwd = 2, col = Ccol)

title("M, C, and T Dynamics Without Parrotfish \n Start with LOW Coral Cover, g = 0.4")

legend(x = 60, y = 1,
       c('Macroalgae', 'Turf Algae', 'Coral'),
       lwd = 2,
       col = c(Mcol, Tcol, Ccol))
```


## Bifurcation diagram of hysteresis
- explaining how Coral cover (C) depends on grazing rate (g)
```{r}
alpha <- 0.1 # coral overgrown by macroalgae at a rate a

# rate macroalgae spread vegetatively over algal turfs per year
gamma <- 0.8 # at a rate γ (gamma)

# rate of coral recruitment to algal turfs per year; coral always overgrow algal turfs
r <- 1 # corals recruit to and overgrow algal turfs at a rate r

# coral mortality -- natural coral mortality accounts for 2-4% per year, predation for 30%, and remaining mortality from coral disease or tissue damage following bleaching
d <- 0.44 # natural mortality rate of d



# setting a g set vector 
g_set <- seq(from = 0, to = 0.55, length.out = 100)


#set for C when it starts low: for region of bistability 
Mset <- NaN*g_set # holding vector for the equilibrium resource population size for each value of Y in Yset
Csetlow <- NaN*g_set # holding vector for N population size for each value of Y in Yset
Tset <- NaN*g_set # holding vector for M population size for each value of Y in Yset


#nested for loop  
for(j in 1:length(g_set)){ # for each element j from 1 to the length of Kset
	g <- g_set[j] # set g equal to the jth element of Kset
	
	# now simulate the model with this vector of Kset:
	# create holding vectors 
  M.simu <- NaN*tset; M.simu[1] <- 0.9
  C.simu <- NaN*tset; C.simu[1] <- 0.05
  T.simu <- NaN*tset; T.simu[1] <- 0.05

for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simu[i-1]
	C <- C.simu[i-1]
	Tt <- T.simu[i-1]
		
	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((g*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simu[i] <- M.simu[i-1] + dM
	C.simu[i] <- C.simu[i-1] + dC
	T.simu[i] <- 1 - C.simu[i] - M.simu[i]
}
	
	# storing population sizes at the last timepoint of our simulation (the equilibrium population sizes) in our holding vectors for equilibrium population sizes 
  Mset[j] <- M.simu[length(tset)] 
	Csetlow[j] <- C.simu[length(tset)] 
	Tset[j] <- T.simu[length(tset)] 
	
}
```

```{r}
#set for C when it starts HIGH: for region of bistability 
Mset <- NaN*g_set # holding vector for the equilibrium resource population size for each value of Y in Yset
Csethigh <- NaN*g_set # holding vector for N population size for each value of Y in Yset
Tset <- NaN*g_set # holding vector for M population size for each value of Y in Yset


#nested for loop  
for(j in 1:length(g_set)){ # for each element j from 1 to the length of Kset
	g <- g_set[j] # set g equal to the jth element of Kset
	
	# now simulate the model with this vector of Kset:
	# create holding vectors 
  M.simu <- NaN*tset; M.simu[1] <- 0.05
  C.simu <- NaN*tset; C.simu[1] <- 0.9
  T.simu <- NaN*tset; T.simu[1] <- 0.05

for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simu[i-1]
	C <- C.simu[i-1]
	Tt <- T.simu[i-1]
		
	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((g*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simu[i] <- M.simu[i-1] + dM
	C.simu[i] <- C.simu[i-1] + dC
	T.simu[i] <- 1 - C.simu[i] - M.simu[i]
}
	
	# storing population sizes at the last timepoint of our simulation (the equilibrium population sizes) in our holding vectors for equilibrium population sizes 
  Mset[j] <- M.simu[length(tset)] 
	Csethigh[j] <- C.simu[length(tset)] 
	Tset[j] <- T.simu[length(tset)] 
	
}
```


plot coral cover vs. grazing rate  
```{r}
# plot grazing as function of Coral cover

plot(x = g_set, y = Csetlow, #plot the grazing bifurcation when coral starts low
     type = 'l', las = 1, lwd = 2, col = '#FFBE9F', 
     xlab = 'Grazing intensity (g)', ylab = 'Equilibrium Coral Cover (C)',
     main = 'Coral Cover vs. Grazing intensity')
lines(x = g_set, y = Csethigh, col = '#DE4800', lwd = 2) #plot the grazing bifurcation when coral starts high

#showing bistability  
rect(xleft = 0.18, ybottom = -1, xright = 0.39, ytop = 0.7, col = rgb(0, 0, 0, alpha = 0.05), lty = 2, border = 1) #ligth grey box to show recovery
text(x = 0.29, y = 0.29, 'Region of Bistability', cex = 0.9) # text to signify bistability
text(x = 0.29, y = 0.54, 'start with high coral cover', cex = 0.6, col = '#DE4800') # text to signify low coral cover 
text(x = 0.29, y = 0.02, 'start with low coral cover', cex = 0.6, col = '#FFBE9F') # text to signify high coral cover 

text(x = 0.13, y = 0.54, 'Gcrit1 = 0.18', cex = 0.9) # text for g crit 1
text(x = 0.44, y = 0.02, 'Gcrit2 = 0.39', cex = 0.9) # text for g crit 2

```

