---
title: "Practice codes"
author: "Maggie Doyle"
date: "2024-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

set up equations 
$$
\begin{align}
\frac{d M}{dt}  &= \alpha M C - \frac{ gM}{(M + T)} + \gamma M T\\ 
\newline
\frac{d C}{dt} &= rTC - dC - \alpha M C\\
\newline
\frac{d T}{dt} &= \frac{ gM}{(M + T)} - \gamma M T + dC\\
\newline
\end{align}
\begin{align}
\frac{d P}{dt} &= \s 
$$

Equations 
```{r}
### Macroalgae ###
# dMdt <- (alpha*M*C) - ((g*M)/(M + T)) + (gamma*M*T)


### Coral ###
# dCdt <- (r*T*C) - (d*C) - (alpha*M*C)


### Turf algae ###
# dTdt <- (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)
```

Parameters 
```{r}
# parrotfish growth rate
s <- 0.49 # intrinsic rate of growth s of parrotfish 

# rate macroalgae directly overgrow coral per year
alpha <- 0.1 # coral overgrown by macroalgae at a rate a

# rate macroalgae spread vegetatively over algal turfs per year
gamma <- 0.8 # at a rate γ (gamma)

# rate of coral recruitment to algal turfs per year; coral always overgrow algal turfs
r <- 1 # corals recruit to and overgrow algal turfs at a rate r

# coral mortality -- natural coral mortality accounts for 2-4% per year, predation for 30%, and remaining mortality from coral disease or tissue damage following bleaching
d <- 0.44 # natural mortality rate of d

# grazing rate g can change, right now im setting it between the critical values 0.18 and 0.39
g <- 0.4 # set grazing rate 

# maximum parrotfish carrying capacity
#beta <- C

```
 
Variables 
```{r}
###  Variables ###

#M <- macroalgae 
  # M <- 1 - C - T
#C <- coral 
  # C <- 1 - M - T
#T <- turf algae 
  # T <- 1 - M - C

# M + C + T = 1 particular region of the seabed is covered entirely by macroalgae (M), coral (C), and algal turfs (T) (variables)

# g # parrotfish graze macroalgae without distinction from algal turfs at a rate g


# storing colors 
Mcol <- 'limegreen' # plot color for macropalgae 
Tcol <- 'darkolivegreen4' # plot color for turf algae 
Ccol <- 'chocolate1' # plot color for coral 
```

setting time and inital values 
```{r}
# time set 0 to 100
tset <- seq(from = 0, to = 100, length.out = 20000) #set time from 0 to 100 

# set initial condition for the parameters, I just set these randomly to be equal to 1 as the paper says
M0 <- 0.5
C0  <- .3
T0  <- 1 - M0 - C0 
P0 <- 1

# creating holding vectors and filling initial conditions
M.simu <- NaN*tset 
M.simu[1] <- M0
T.simu <- NaN*tset
T.simu[1] <- T0
C.simu <- NaN*tset
C.simu[1] <- C0
P.simu <- NaN*tset
P.simu[1] <- P0 #start P squiggle (only using P squiggle, so P squiggle = P; g = P squiggle because g(P) = P/beta, and we assume beta = 1 (max carrying capacity, which is the same as max coral cover), so setting initial g value to P0

```

for loop 
```{r}
### M, C, T dynamis in the absence of parrotfish grazing

for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simu[i-1]
	C <- C.simu[i-1]
	Tt <- T.simu[i-1]
		

	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((P*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	
	# calculating total population size
	M.simu[i] <- M.simu[i-1] + dM
	C.simu[i] <- C.simu[i-1] + dC
	T.simu[i] <- 1 - C.simu[i] - M.simu[i]
}
```


```{r}
# plot macroalgae
plot(x = tset, y = M.simu,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Proportion of Coral, Turf and Macroalgae',
     xlim = c(min(tset), max(tset)), ylim = c(0, 1))
# plot turf
lines(x = tset, y = T.simu,
      lwd = 2, col = Tcol)
# plot coral
lines(x = tset, y = C.simu,
      lwd = 2, col = Ccol)

title("M, C, and T dynamics without parrotfish")

legend(x = 60, y = 1,
       c('Macroalgae', 'Turf Algae', 'Coral'),
       lwd = 2,
       col = c(Mcol, Tcol, Ccol))
```

```{r}
#### WITH PARROTFISH POPULATIONS ####
# parrotfish logistic growth changes the grazing rate (g = P, see model assumptions) and therefore impacts M, C, and T dynamics
# f = 0 
# beta = K(C) = C
# simu2

# creating holding vectors and filling initial conditions
M.simu2 <- NaN*tset 
M.simu2[1] <- M0
T.simu2 <- NaN*tset
T.simu2[1] <- T0
C.simu2 <- NaN*tset
C.simu2[1] <- C0
P.simu2 <- NaN*tset
P.simu2[1] <- P0

for(i in 2:length(tset)){
  # calculating change in time
	dt <- tset[i]-tset[i-1] 
	
	# set variable equal to the simulation value at the previous timestep
	M <- M.simu2[i-1]
	C <- C.simu2[i-1]
	Tt <- T.simu2[i-1]
	P <- P.simu2[i-1]
		

	# calculating change in population size -- replace g with P squiggle (P)
	dM <- ( (alpha*M*C) - ((P*M)/(M + Tt)) + (gamma*M*Tt) ) * dt 
	#dT <- ( (g*M)/(M + T) - (gamma*M*T) - (r*T*C) + (d*C)) * dt 
	dC <- ((r*Tt*C) - (d*C) - (alpha*M*C) ) * dt
	# parrotfish population growth, assuming f = 0, and max carrying capacity = C
	dP <- ((s*P)*(1 - (P/C))) * dt
	
	# calculating total population size
	M.simu2[i] <- M.simu2[i-1] + dM
	C.simu2[i] <- C.simu2[i-1] + dC
	T.simu2[i] <- 1 - C.simu2[i] - M.simu2[i]
	### add equation here to have g change as P changes -- with the assumptions of the model, we can set g = P squiggle (here just P)
	P.simu2[i] <- P.simu2[i-1] + dP
}

```

```{r}
# plot macroalgae
plot(x = tset, y = M.simu2,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Proportion of Coral, Turf and Macroalgae',
     xlim = c(min(tset), max(tset)), ylim = c(0, 1))
# plot turf
lines(x = tset, y = T.simu2,
      lwd = 2, col = Tcol)
# plot coral
lines(x = tset, y = C.simu2,
      lwd = 2, col = Ccol)

title("M, C, and T dynamics with parrotfish grazing")

legend(x = 60, y = 1,
       c('Macroalgae', 'Turf Algae', 'Coral'),
       lwd = 2,
       col = c(Mcol, Tcol, Ccol))
```

```{r}
# plot macroalgae
plot(x = tset, y = P.simu2,
     type = 'l', las = 1, lwd = 2, col = Mcol,
     xlab = 'Time', ylab = 'Parrotfish Population Size')

title("Parrotfish Population Growth")

```

